# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SensorService.proto\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"^\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\r\x12\r\n\x05month\x18\x02 \x01(\r\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\r\x12\x0c\n\x04hour\x18\x04 \x01(\r\x12\x0e\n\x06minute\x18\x05 \x01(\r\x12\x0e\n\x06second\x18\x06 \x01(\r\"$\n\x0cLocalization\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"`\n\x0fTemperatureData\x12\x13\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x05.Date\x12#\n\x0clocalization\x18\x02 \x01(\x0b\x32\r.Localization\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\"5\n\x13ListTemperatureData\x12\x1e\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x10.TemperatureData\"I\n\x11LocalizationRange\x12\x19\n\x02l1\x18\x01 \x01(\x0b\x32\r.Localization\x12\x19\n\x02l2\x18\x02 \x01(\x0b\x32\r.Localization\"1\n\tDateRange\x12\x11\n\x02\x64\x31\x18\x01 \x01(\x0b\x32\x05.Date\x12\x11\n\x02\x64\x32\x18\x02 \x01(\x0b\x32\x05.Date2\xcf\x01\n\rSensorService\x12\x36\n\x12\x41\x64\x64TemperatureData\x12\x10.TemperatureData\x1a\x0c.StatusReply\"\x00\x12J\n\x1cGetTemperatureByLocalization\x12\x12.LocalizationRange\x1a\x14.ListTemperatureData\"\x00\x12:\n\x14GetTemperatureByDate\x12\n.DateRange\x1a\x14.ListTemperatureData\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSREPLY._serialized_start=23
  _STATUSREPLY._serialized_end=52
  _DATE._serialized_start=54
  _DATE._serialized_end=148
  _LOCALIZATION._serialized_start=150
  _LOCALIZATION._serialized_end=186
  _TEMPERATUREDATA._serialized_start=188
  _TEMPERATUREDATA._serialized_end=284
  _LISTTEMPERATUREDATA._serialized_start=286
  _LISTTEMPERATUREDATA._serialized_end=339
  _LOCALIZATIONRANGE._serialized_start=341
  _LOCALIZATIONRANGE._serialized_end=414
  _DATERANGE._serialized_start=416
  _DATERANGE._serialized_end=465
  _SENSORSERVICE._serialized_start=468
  _SENSORSERVICE._serialized_end=675
# @@protoc_insertion_point(module_scope)
